# Generated by Django 3.2.11 on 2022-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alm_Inventario',
            fields=[
                ('INV_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('INV_ST_USUARIO', models.CharField(max_length=20, verbose_name='usuario')),
                ('INV_DT_MOVIMENTO', models.DateField(blank=True, null=True, verbose_name='data')),
                ('INV_CH_STATUS', models.CharField(max_length=1, verbose_name='status')),
                ('FIL_IN_CODIGO', models.IntegerField(blank=True, null=True, verbose_name='filial')),
                ('INV_ID_CCUSTO', models.CharField(blank=True, max_length=18, null=True, verbose_name='centro de custo')),
                ('INT_IN_SEQUENCIA', models.IntegerField(blank=True, null=True, verbose_name='sequencial')),
            ],
            options={
                'db_table': 'alm_Inventario',
            },
        ),
        migrations.CreateModel(
            name='alm_InventarioItens',
            fields=[
                ('ITI_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ITI_ID_PRODUTO', models.CharField(max_length=22, verbose_name='item')),
                ('ITI_RE_QUANTIDADE', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade')),
                ('ITI_CH_STATUS', models.CharField(max_length=1, verbose_name='status')),
                ('MOV_IN_SEQUENCIA', models.IntegerField(blank=True, null=True, verbose_name='sequencial')),
                ('INV_IN_SEQUENCIA', models.IntegerField(blank=True, null=True, verbose_name='id inventario')),
                ('ITI_ST_TIPOMOV', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo')),
                ('MOI_IN_SEQUENCIA', models.IntegerField(blank=True, null=True, verbose_name='sequencial_item')),
            ],
            options={
                'db_table': 'alm_InventarioItens',
            },
        ),
    ]
