# Generated by Django 3.2.11 on 2022-09-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alm_inventario',
            old_name='INT_IN_SEQUENCIA',
            new_name='MOV_IN_SEQUENCIA',
        ),
    ]
