# Generated by Django 3.2.11 on 2023-01-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_int_in_sequencia_alm_inventario_mov_in_sequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alm_inventarioitens',
            name='INV_IN_SEQUENCIA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.alm_inventario', verbose_name='id inventario'),
        ),
    ]
