# Generated by Django 3.2.11 on 2023-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_alm_inventarioitens_inv_in_sequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alm_inventarioitens',
            name='INV_IN_SEQUENCIA',
            field=models.IntegerField(verbose_name='id inventario'),
        ),
    ]
