# Generated by Django 3.2.11 on 2022-06-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bxa_AlmoxaBaixa',
            fields=[
                ('BXA_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False, verbose_name='sequencial baixa')),
                ('BXA_DT_APONTAMENTO', models.DateField(verbose_name='data')),
                ('BXA_ST_USUARIO', models.CharField(max_length=20, verbose_name='usuario')),
                ('BXA_IN_CCUSTO', models.IntegerField(blank=True, null=True)),
                ('BXA_CH_STATUS', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'bxa_AlmoxaBaixa',
            },
        ),
        migrations.CreateModel(
            name='bxi_AlmoxaBaixaItens',
            fields=[
                ('BXI_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False, verbose_name='sequencial Item')),
                ('BXA_IN_SEQUENCIA', models.IntegerField(blank=True, null=True)),
                ('BXI_ID_PRODUTO', models.CharField(max_length=22, verbose_name='item')),
                ('BXI_RE_QUANTIDADE', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade')),
                ('BXI_CH_STATUS', models.CharField(max_length=1, verbose_name='status')),
            ],
            options={
                'db_table': 'bxi_AlmoxaBaixaItens',
            },
        ),
    ]
