# Generated by Django 3.2.11 on 2022-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bxa_CentroCustos',
            fields=[
                ('CUS_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CUS_TAB_IN_CODIGO', models.IntegerField(blank=True, null=True)),
                ('CUS_PAD_IN_CODIGO', models.IntegerField(blank=True, null=True)),
                ('CUS_IDE_ST_CODIGO', models.CharField(max_length=5, verbose_name='IDE')),
                ('CUS_IN_REDUZIDO', models.IntegerField(blank=True, null=True)),
                ('CUS_ST_EXTENSO', models.CharField(max_length=25, verbose_name='EXTENSO')),
                ('CUS_ST_DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'db_table': 'bxa_CentroCustos',
            },
        ),
    ]
