# Generated by Django 3.2.11 on 2022-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_bxa_centrocustos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxa_centrocustos',
            name='CUS_IN_SEQUENCIA',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
