# Generated by Django 3.2.11 on 2022-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_alter_bxa_centrocustos_cus_in_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxa_almoxabaixa',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
