# Generated by Django 3.2.11 on 2022-07-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_bxa_almoxabaixa_fil_in_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bxa_almoxabaixa',
            old_name='BXA_IN_CCUSTO',
            new_name='BXA_ST_CCUSTO',
        ),
        migrations.RemoveField(
            model_name='bxa_almoxabaixa',
            name='FIL_IN_CODIGO',
        ),
    ]
