# Generated by Django 3.2.11 on 2022-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_auto_20220705_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bxa_almoxabaixa',
            old_name='BXA_ST_CCUSTO',
            new_name='BXA_IN_CCUSTO',
        ),
        migrations.AddField(
            model_name='bxa_almoxabaixa',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
