# Generated by Django 3.2.11 on 2022-07-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_auto_20220705_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='est_CadItens',
            fields=[
                ('BXI_ID_PRODUTO', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='item')),
                ('PRO_TAB_IN_CODIGO', models.IntegerField()),
                ('PRO_PAD_IN_CODIGO', models.IntegerField()),
                ('PRO_IN_CODIGO', models.IntegerField()),
            ],
            options={
                'db_table': 'est_CadItens',
            },
        ),
    ]
