# Generated by Django 3.2.11 on 2022-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0007_est_caditens'),
    ]

    operations = [
        migrations.AddField(
            model_name='est_caditens',
            name='PRO_ST_DESCRICAO',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='est_caditens',
            name='UNI_ST_UNIDADE',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='UM'),
        ),
    ]
