# Generated by Django 3.2.11 on 2022-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_auto_20220705_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='est_caditens',
            name='BXI_ID_PRODUTO',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='ITEM'),
        ),
    ]
