# Generated by Django 3.2.11 on 2022-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_alter_est_caditens_bxi_id_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='est_caditens',
            name='PRO_IN_CODIGO',
            field=models.IntegerField(verbose_name='PRODUTO'),
        ),
        migrations.AlterField(
            model_name='est_caditens',
            name='PRO_PAD_IN_CODIGO',
            field=models.IntegerField(verbose_name='PADRÃO'),
        ),
        migrations.AlterField(
            model_name='est_caditens',
            name='PRO_ST_DESCRICAO',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='DESCRIÇÃO'),
        ),
        migrations.AlterField(
            model_name='est_caditens',
            name='PRO_TAB_IN_CODIGO',
            field=models.IntegerField(verbose_name='TABELA'),
        ),
    ]
