# Generated by Django 3.2.11 on 2022-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_auto_20220705_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxa_centrocustos',
            name='CUS_IN_SEQUENCIA',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
