# Generated by Django 3.2.11 on 2022-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_alter_bxa_centrocustos_cus_in_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxa_centrocustos',
            name='CUS_ID_CCUSTO',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
