# Generated by Django 3.2.11 on 2022-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0012_bxa_centrocustos_cus_id_ccusto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bxa_centrocustos',
            old_name='CUS_ID_CCUSTO',
            new_name='CUS_ID_CCUSTO2',
        ),
        migrations.AlterField(
            model_name='bxa_centrocustos',
            name='CUS_IN_SEQUENCIA',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID2'),
        ),
    ]
