# Generated by Django 3.2.11 on 2022-07-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0013_auto_20220705_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxa_centrocustos',
            name='CUS_ID_CCUSTO2',
        ),
    ]
