# Generated by Django 3.2.11 on 2022-07-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0014_remove_bxa_centrocustos_cus_id_ccusto2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bxa_centrocustos',
            old_name='CUS_IN_SEQUENCIA',
            new_name='CUS_ID_CCUSTO',
        ),
    ]
