# Generated by Django 3.2.11 on 2022-07-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0015_rename_cus_in_sequencia_bxa_centrocustos_cus_id_ccusto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxa_centrocustos',
            name='CUS_ID_CCUSTO',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='ID2'),
        ),
    ]
