# Generated by Django 3.2.11 on 2022-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_alter_bxa_centrocustos_cus_id_ccusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxa_almoxabaixa',
            name='CUS_ID_CCUSTO',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Id_CCusto'),
        ),
    ]
