# Generated by Django 3.2.11 on 2022-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0018_bxa_almoxabaixa_cus_id_ccusto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxa_almoxabaixa',
            name='CUS_ID_CCUSTO',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='id_ccusto'),
        ),
    ]
