# Generated by Django 3.2.11 on 2022-07-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0019_alter_bxa_almoxabaixa_cus_id_ccusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxi_almoxabaixaitens',
            name='BXI_ID_REQUISICAO',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_sequencial'),
        ),
    ]
