# Generated by Django 3.2.11 on 2022-07-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0020_bxi_almoxabaixaitens_bxi_id_requisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxi_almoxabaixaitens',
            name='BXI_ID_REQUISICAO',
        ),
    ]
