# Generated by Django 3.2.11 on 2022-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0021_remove_bxi_almoxabaixaitens_bxi_id_requisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxi_almoxabaixaitens',
            name='BXI_ID_REQUISICAO',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_sequencial'),
        ),
    ]
