# Generated by Django 3.2.11 on 2022-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0022_bxi_almoxabaixaitens_bxi_id_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxi_almoxabaixaitens',
            name='BXI_ID_REQUISICAO',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id_sequencial'),
        ),
        migrations.AlterField(
            model_name='bxi_almoxabaixaitens',
            name='BXI_IN_SEQUENCIA',
            field=models.IntegerField(verbose_name='sequencial Item'),
        ),
    ]
