# Generated by Django 3.2.11 on 2022-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0023_auto_20220712_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxa_almoxabaixa',
            name='REQ_IN_SEQUENCIA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bxi_almoxabaixaitens',
            name='REI_IN_SEQUENCIA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bxi_almoxabaixaitens',
            name='REQ_IN_SEQUENCIA',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
