# Generated by Django 3.2.11 on 2022-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0024_auto_20220725_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='est_CadItemAlmoxa',
            fields=[
                ('LOC_ID_PROALMFIL', models.CharField(max_length=38, primary_key=True, serialize=False, verbose_name='ID_PROALMFIL')),
                ('LOC_ID_ALMOXA', models.CharField(max_length=18, verbose_name='ID_ALMOXA')),
                ('LOC_ID_ORG', models.CharField(max_length=16, verbose_name='ID_ORG')),
                ('LOC_ID_PRODUTO', models.CharField(max_length=13, verbose_name='ID_ITEM')),
                ('LOC_IN_FILIAL', models.IntegerField(verbose_name='FILIAL')),
                ('ALM_IN_CODIGO', models.IntegerField(verbose_name='ALMOXARIFADO')),
                ('LOC_IN_CODIGO', models.IntegerField(verbose_name='LOCALIZAÇÃO')),
            ],
            options={
                'db_table': 'est_CadItemAlmoxa',
            },
        ),
    ]
