# Generated by Django 3.2.11 on 2022-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0025_est_caditemalmoxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='est_caditemalmoxa',
            name='ALM_ST_DESCRICAO',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DESC_ALMOXA'),
        ),
        migrations.AddField(
            model_name='est_caditemalmoxa',
            name='LOC_ST_DESCRICAO',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='DESC_LOCAL'),
        ),
    ]
