# Generated by Django 3.2.11 on 2022-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0026_auto_20221214_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxi_almoxabaixaitens',
            name='BXI_ID_ALMOXA',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='DESTINO'),
        ),
    ]
