# Generated by Django 3.2.11 on 2023-01-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0027_bxi_almoxabaixaitens_bxi_id_almoxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxi_almoxabaixaitens',
            name='BXA_IN_SEQUENCIA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.bxa_almoxabaixa', verbose_name='Id Baixa'),
        ),
    ]
