# Generated by Django 3.2.11 on 2023-01-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0028_alter_bxi_almoxabaixaitens_bxa_in_sequencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bxi_almoxabaixaitens',
            old_name='BXA_IN_SEQUENCIA',
            new_name='BXA_IN_SEQUENCIA_ID',
        ),
    ]
