# Generated by Django 3.2.11 on 2023-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0030_rename_bxa_in_sequencia_id_bxi_almoxabaixaitens_bxa_in_sequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxi_almoxabaixaitens',
            name='BXA_IN_SEQUENCIA',
            field=models.IntegerField(verbose_name='Id Baixa'),
        ),
    ]
