# Generated by Django 3.2.11 on 2023-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0031_alter_bxi_almoxabaixaitens_bxa_in_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxa_almoxabaixa',
            name='OS_ST_ID',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='id_os'),
        ),
    ]
