# Generated by Django 3.2.11 on 2024-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0032_bxa_almoxabaixa_os_st_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxi_almoxabaixaitens',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
