# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Nome')),
                ('adress', models.CharField(max_length=100, verbose_name=b'Endere\xc3\xa7o')),
                ('city', models.CharField(max_length=50, verbose_name=b'Cidade')),
                ('cep', models.CharField(max_length=50, verbose_name=b'Cep')),
                ('phone', models.CharField(max_length=20, verbose_name=b'Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name=b'Celular')),
                ('about', models.TextField(max_length=255, verbose_name=b'Sobre')),
                ('data_nascimento', models.CharField(default=b'01 de janeiro de 2000', max_length=255, verbose_name=b'Data Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('conhecimentos', models.TextField(max_length=255, verbose_name=b'Conhecimentos')),
                ('github', models.CharField(default=b'http://github.com/SeuGit', max_length=100, verbose_name=b'Github')),
                ('current_position', models.CharField(max_length=100, verbose_name=b'Cargo atual')),
                ('empresa', models.CharField(max_length=100, verbose_name=b'Empresa')),
            ],
            options={
                'verbose_name': 'Dados Pessoais',
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
    ]
