# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-10-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APT_APONTAORDEM',
            fields=[
                ('apt_in_sequencia', models.AutoField(primary_key=True, serialize=False)),
                ('apt_dt_apontamento', models.DateField()),
                ('apt_ati_tab_in_codigo', models.IntegerField()),
                ('apt_ati_pad_in_codigo', models.IntegerField()),
                ('apt_ati_in_codigo', models.IntegerField()),
                ('apt_ch_status', models.CharField(max_length=1)),
                ('org_tab_in_codigo', models.IntegerField()),
                ('org_pad_in_codigo', models.IntegerField()),
                ('org_in_codigo', models.IntegerField()),
                ('org_tau_st_codigo', models.CharField(max_length=3)),
                ('fil_in_codigo', models.IntegerField()),
                ('ord_tab_in_codigo', models.IntegerField()),
                ('ord_seq_in_codigo', models.IntegerField()),
                ('ord_in_codigo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Apontamentos Ordens',
                'verbose_name_plural': 'Apontamentos Ordens',
            },
        ),
    ]
