# Generated by Django 3.2.11 on 2022-01-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apt_apontaordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='about',
            field=models.TextField(max_length=255, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='cep',
            field=models.CharField(max_length=50, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='conhecimentos',
            field=models.TextField(max_length=255, verbose_name='Conhecimentos'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='current_position',
            field=models.CharField(max_length=100, verbose_name='Cargo atual'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.CharField(default='01 de janeiro de 2000', max_length=255, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='github',
            field=models.CharField(default='http://github.com/SeuGit', max_length=100, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
