# Generated by Django 3.2.11 on 2022-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='man_pro_ordens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_tab_in_codigo', models.IntegerField()),
                ('org_pad_in_codigo', models.IntegerField()),
                ('org_in_codigo', models.IntegerField()),
                ('org_tau_st_codigo', models.CharField(max_length=3)),
                ('ord_tab_in_codigo', models.IntegerField()),
                ('ord_seq_in_codigo', models.IntegerField()),
                ('ord_in_codigo', models.IntegerField()),
                ('pro_tab_in_codigo', models.IntegerField()),
                ('pro_pad_in_codigo', models.IntegerField()),
                ('pro_in_codigo', models.IntegerField()),
                ('ord_re_qtde_ordem', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
            options={
                'db_table': 'man_pro_ordens',
            },
        ),
        migrations.CreateModel(
            name='Apt_ApontaOrdem',
            fields=[
                ('FIL_IN_CODIGO', models.IntegerField()),
                ('APT_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False)),
                ('APT_DT_APONTAMENTO', models.DateField()),
                ('APT_CH_STATUS', models.CharField(max_length=1)),
                ('ORD_IN_CODIGO', models.IntegerField()),
                ('PRO_IN_CODIGO', models.IntegerField()),
                ('ORL_RE_QTDLOTE', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ORL_ST_REFERENCIA', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Apt_ApontaOrdem',
            },
        ),
        migrations.CreateModel(
            name='Apt_Ocorrencia',
            fields=[
                ('ATI_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False)),
                ('ATI_IN_CODIGO', models.IntegerField()),
                ('ATI_DT_INCLUSAO', models.DateTimeField()),
                ('ATI_USU_INCLUSAO', models.CharField(max_length=20)),
                ('ATI_IN_ORDEM', models.IntegerField()),
                ('ATI_IN_TEMPO', models.IntegerField()),
            ],
            options={
                'db_table': 'Apt_Ocorrencia',
            },
        ),
        migrations.CreateModel(
            name='Apt_Pro_Demandas',
            fields=[
                ('FIL_IN_CODIGO', models.IntegerField()),
                ('MOV_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False)),
                ('MOV_DT_INCLUSAO', models.DateField()),
                ('PRO_IN_CODIGO', models.IntegerField()),
                ('ORD_IN_CODIGO', models.IntegerField()),
                ('PRO_RE_QTDLOTE', models.DecimalField(decimal_places=3, max_digits=10)),
                ('PRO_ST_LOTE', models.CharField(max_length=50)),
                ('MOV_ST_STATUS', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Apt_Pro_Demandas',
            },
        ),
    ]
