# Generated by Django 3.2.11 on 2022-02-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='ord_in_codigo',
            new_name='ORD_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='ord_re_qtde_ordem',
            new_name='ORD_RE_QTDE_ORDEM',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='ord_seq_in_codigo',
            new_name='ORD_SEQ_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='ord_tab_in_codigo',
            new_name='ORD_TAB_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='org_in_codigo',
            new_name='ORG_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='org_pad_in_codigo',
            new_name='ORG_PAD_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='org_tab_in_codigo',
            new_name='ORG_TAB_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='org_tau_st_codigo',
            new_name='ORG_TAU_ST_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='pro_in_codigo',
            new_name='PRO_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='pro_pad_in_codigo',
            new_name='PRO_PAD_IN_CODIGO',
        ),
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='pro_tab_in_codigo',
            new_name='PRO_TAB_IN_CODIGO',
        ),
    ]
