# Generated by Django 3.2.11 on 2022-02-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220224_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='id',
            new_name='ID',
        ),
    ]
