# Generated by Django 3.2.11 on 2022-02-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_id_man_pro_ordens_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='man_pro_ordens',
            old_name='ID',
            new_name='TAB_IN_SEQUENCIA',
        ),
    ]
