# Generated by Django 3.2.11 on 2022-02-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_id_man_pro_ordens_tab_in_sequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='man_itens_ordens',
            fields=[
                ('TAB_IN_SEQUENCIA', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRO_TAB_IN_CODIGO', models.IntegerField()),
                ('PRO_PAD_IN_CODIGO', models.IntegerField()),
                ('PRO_IN_CODIGO', models.IntegerField()),
                ('PRO_ST_DESCRICAO', models.CharField(max_length=3)),
                ('UNI_ST_UNIDADE', models.CharField(max_length=3)),
                ('RFC_IN_CODIGO', models.IntegerField()),
                ('PRO_ST_ATRIBUTOS', models.TextField(blank=True, null=True)),
                ('PRO_ST_REFERENCIA', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'man_itens_ordens',
            },
        ),
        migrations.AddField(
            model_name='man_pro_ordens',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
