# Generated by Django 3.2.11 on 2022-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220225_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man_itens_ordens',
            name='PRO_ST_DESCRICAO',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='man_itens_ordens',
            name='UNI_ST_UNIDADE',
            field=models.CharField(max_length=8),
        ),
    ]
