# Generated by Django 3.2.11 on 2022-02-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220225_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man_itens_ordens',
            name='PRO_ST_ATRIBUTOS',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='man_itens_ordens',
            name='PRO_ST_REFERENCIA',
            field=models.JSONField(default='{}'),
        ),
    ]
