# Generated by Django 3.2.11 on 2022-02-26 02:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220225_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man_itens_ordens',
            name='PRO_ST_ATRIBUTOS',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='man_itens_ordens',
            name='PRO_ST_REFERENCIA',
            field=jsonfield.fields.JSONField(),
        ),
    ]
