# Generated by Django 3.2.11 on 2022-03-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220225_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='apt_pro_atividade',
            fields=[
                ('TAB_IN_SEQUENCIA', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATI_TAB_IN_CODIGO', models.IntegerField()),
                ('ATI_PAD_IN_CODIGO', models.IntegerField()),
                ('ATI_IN_CODIGO', models.IntegerField()),
                ('ATI_ST_NOME', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'apt_pro_atividade',
            },
        ),
        migrations.RenameModel(
            old_name='man_itens_ordens',
            new_name='apt_itens_ordens',
        ),
        migrations.RenameModel(
            old_name='man_pro_ordens',
            new_name='apt_pro_ordens',
        ),
        migrations.AlterModelTable(
            name='apt_itens_ordens',
            table='apt_itens_ordens',
        ),
        migrations.AlterModelTable(
            name='apt_pro_ordens',
            table='apt_pro_ordens',
        ),
    ]
