# Generated by Django 3.2.11 on 2022-03-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220302_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='PRO_ST_DEMANDAS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='PRO_ST_ITENS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
