# Generated by Django 3.2.11 on 2022-03-02 17:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220302_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='PRO_ST_DEMANDAS',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='PRO_ST_ITENS',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
