# Generated by Django 3.2.11 on 2022-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220302_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='CTL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apt_pro_demandas',
            name='CTL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
