# Generated by Django 3.2.11 on 2022-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220303_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_ST_DESCRICAO',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
