# Generated by Django 3.2.11 on 2022-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_apt_apontaordem_pro_st_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='PRO_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
