# Generated by Django 3.2.11 on 2022-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_apt_pro_demandas_pro_in_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_itens_ordens',
            name='PRO_ST_MEDIDAS',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
