# Generated by Django 3.2.11 on 2022-03-07 21:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_apt_itens_ordens_pro_st_medidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_itens_ordens',
            name='PRO_ST_MEDIDAS',
            field=jsonfield.fields.JSONField(),
        ),
    ]
