# Generated by Django 3.2.11 on 2022-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_apt_itens_ordens_pro_st_medidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='TPO_ST_CODIGO',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
