# Generated by Django 3.2.11 on 2022-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_apt_pro_ordens_tpo_st_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='apt_tb_tabfilseqlote',
            fields=[
                ('TSEQ_IN_SEQUENCIA', models.IntegerField(primary_key=True, serialize=False, verbose_name='SEQ')),
                ('ORG_TAB_IN_CODIGO', models.IntegerField()),
                ('ORG_PAD_IN_CODIGO', models.IntegerField()),
                ('ORG_IN_CODIGO', models.IntegerField()),
                ('FIL_IN_CODIGO', models.IntegerField()),
                ('ORG_TAU_ST_CODIGO', models.CharField(max_length=3)),
                ('TAB_IN_CODIGO', models.IntegerField()),
                ('PAD_IN_CODIGO', models.IntegerField()),
            ],
            options={
                'db_table': 'apt_tb_tabfilseqlote',
            },
        ),
    ]
