# Generated by Django 3.2.11 on 2022-03-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_apt_tb_tabfilseqlote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apt_tb_tabfilseqlote',
            name='FIL_IN_CODIGO',
        ),
        migrations.RemoveField(
            model_name='apt_tb_tabfilseqlote',
            name='ORG_IN_CODIGO',
        ),
        migrations.RemoveField(
            model_name='apt_tb_tabfilseqlote',
            name='ORG_PAD_IN_CODIGO',
        ),
        migrations.RemoveField(
            model_name='apt_tb_tabfilseqlote',
            name='ORG_TAB_IN_CODIGO',
        ),
        migrations.RemoveField(
            model_name='apt_tb_tabfilseqlote',
            name='ORG_TAU_ST_CODIGO',
        ),
        migrations.RemoveField(
            model_name='apt_tb_tabfilseqlote',
            name='PAD_IN_CODIGO',
        ),
    ]
