# Generated by Django 3.2.11 on 2022-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220321_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_ST_LOTE',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
