# Generated by Django 3.2.11 on 2022-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_apt_apontaordem_pro_st_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='PRO_ST_LOTE',
            field=models.CharField(max_length=22),
        ),
    ]
