# Generated by Django 3.2.11 on 2022-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_apt_apontaordem_pro_st_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_ST_SEQUENCIAL',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
