# Generated by Django 3.2.11 on 2022-04-04 17:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_apt_apontaordem_pro_st_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='PRO_ST_ETIQUETA',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
