# Generated by Django 3.2.11 on 2022-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_apt_apontaordem_pro_st_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='RFC_ST_DESCRICAO',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
