# Generated by Django 3.2.11 on 2022-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_apt_apontaordem_rfc_st_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_RE_QTDREFUGO',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
