# Generated by Django 3.2.11 on 2022-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_apt_apontaordem_pro_re_qtdrefugo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_RE_QTDCONV',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
