# Generated by Django 3.2.11 on 2022-07-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_apt_apontaordem_pro_re_qtdconv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='APT_CH_STATUS',
            field=models.CharField(max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='APT_DT_APONTAMENTO',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='APT_IN_SEQUENCIA',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='sequencial'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='ORD_IN_CODIGO',
            field=models.IntegerField(verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='ORL_RE_QTDLOTE',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='PRO_IN_CODIGO',
            field=models.IntegerField(verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='PRO_RE_QTDREFUGO',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='refugo'),
        ),
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='PRO_ST_LOTE',
            field=models.CharField(max_length=22, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='apt_pro_atividade',
            name='ATI_IN_CODIGO',
            field=models.IntegerField(verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='apt_pro_atividade',
            name='ATI_ST_NOME',
            field=models.CharField(max_length=60, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='CTL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='controle'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='MOV_DT_INCLUSAO',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='MOV_IN_SEQUENCIA',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='sequencial'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='MOV_ST_STATUS',
            field=models.CharField(max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='ORD_IN_CODIGO',
            field=models.IntegerField(verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='PRO_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='PRO_RE_QTDLOTE',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='apt_pro_demandas',
            name='PRO_ST_LOTE',
            field=models.CharField(max_length=50, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='filial'),
        ),
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='ORD_IN_CODIGO',
            field=models.IntegerField(verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='ORD_RE_QTDE_ORDEM',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='PRO_IN_CODIGO',
            field=models.IntegerField(verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='apt_pro_ordens',
            name='TPO_ST_CODIGO',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo'),
        ),
    ]
