# Generated by Django 3.2.11 on 2022-08-30 21:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220725_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='PRO_ST_INFOADIC',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
