# Generated by Django 3.2.11 on 2022-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_apt_pro_ordens_pro_st_infoadic'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_ST_LOTEORI',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
