# Generated by Django 3.2.11 on 2022-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_apt_apontaordem_pro_st_loteori'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_itens_ordens',
            name='MVS_ST_REFERENCIA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
