# Generated by Django 3.2.11 on 2022-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_apt_itens_ordens_mvs_st_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_itens_ordens',
            name='PRO_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ITEM'),
        ),
    ]
