# Generated by Django 3.2.11 on 2022-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_apt_itens_ordens_pro_st_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='ORD_ST_ID',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='id_ordem'),
        ),
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='id_item'),
        ),
        migrations.AddField(
            model_name='apt_pro_demandas',
            name='ORD_ST_ID',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='id_ordem'),
        ),
        migrations.AddField(
            model_name='apt_pro_demandas',
            name='PRO_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='id_item'),
        ),
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='ORD_ST_ID',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='ORDEM'),
        ),
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='PRO_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ITEM'),
        ),
    ]
