# Generated by Django 3.2.11 on 2022-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20221003_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='CMAQ_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='id_maquina'),
        ),
    ]
