# Generated by Django 3.2.11 on 2023-04-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_apt_apontaordem_cmaq_st_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt_ResumoOrdem',
            fields=[
                ('RES_ST_ID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RES_ID')),
                ('RES_IN_CODIGO', models.IntegerField(verbose_name='CODIGO')),
                ('RES_IN_SEQUENCIA', models.IntegerField(verbose_name='SEQUENCIA')),
                ('ORD_ST_ID', models.CharField(max_length=42, verbose_name='ORDEM')),
                ('PRO_ST_ID', models.CharField(max_length=13, verbose_name='ID_ITEM')),
                ('PRO_RE_QTDINFORMADA', models.DecimalField(decimal_places=3, max_digits=10)),
                ('RES_ST_STATUS', models.CharField(max_length=1, verbose_name='STATUS')),
                ('PRO_IN_CODIGO', models.IntegerField(blank=True, null=True, verbose_name='ITEM')),
                ('PRO_ST_DESCRICAO', models.CharField(blank=True, max_length=70, null=True, verbose_name='DESCRICAO')),
                ('PRO_RE_QTDORIGINAL', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Apt_ResumoOrdem',
            },
        ),
        migrations.AddField(
            model_name='apt_apontaordem',
            name='ORL_RE_QTDAJUSTADA',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apt_apontaordem',
            name='RES_ST_ID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='seq_resumo'),
        ),
        migrations.AddField(
            model_name='apt_apontaordem',
            name='RES_ST_STATUS',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
