# Generated by Django 3.2.11 on 2023-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20230417_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt_EstFormatos',
            fields=[
                ('PUN_ST_ID', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='PUN_ID')),
                ('FMT_ST_ID', models.CharField(blank=True, max_length=10, null=True, verbose_name='FMT_ID')),
                ('PRO_ST_ID', models.CharField(blank=True, max_length=13, null=True, verbose_name='PRO_ID')),
                ('FMT_ST_CODIGO', models.CharField(blank=True, max_length=4, null=True, verbose_name='CONVERSOR')),
                ('FMT_ST_NOME', models.CharField(blank=True, max_length=30, null=True, verbose_name='DESCRICAO')),
                ('UNI_ST_UNIDADE', models.CharField(blank=True, max_length=8, null=True, verbose_name='UNIDADE')),
                ('FMT_ST_FORMULA', models.CharField(blank=True, max_length=200, null=True, verbose_name='FORMULA')),
            ],
            options={
                'db_table': 'Apt_EstFormatos',
            },
        ),
        migrations.AddField(
            model_name='apt_pro_demandas',
            name='CMAQ_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='id_maquina'),
        ),
    ]
