# Generated by Django 3.2.11 on 2023-10-30 19:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20230509_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt_ProMaquinaConfig',
            fields=[
                ('CFG_ST_ID', models.CharField(max_length=39, primary_key=True, serialize=False, verbose_name='CFG_ID')),
                ('CTR_ST_ID', models.CharField(blank=True, max_length=13, null=True, verbose_name='id_centro')),
                ('CMAQ_ST_ID', models.CharField(blank=True, max_length=13, null=True, verbose_name='id_maquina')),
                ('OPR_ST_ID', models.CharField(blank=True, max_length=13, null=True, verbose_name='id_operacao')),
                ('CUS_BO_NAOBAIXADEMANDA', models.CharField(default='N', max_length=1, verbose_name='Não Baixa Demanda')),
                ('CUS_BO_GERASEQPALLET', models.CharField(default='N', max_length=1, verbose_name='Controla Sequencial de Pallet')),
                ('CUS_BO_CONVERSOR', models.CharField(default='N', max_length=1, verbose_name='Utiliza Conversor')),
                ('CUS_BO_LOTES', models.CharField(default='N', max_length=1, verbose_name='Gera Multiplos Lotes')),
                ('OPR_ST_OPERACAO', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição da operação')),
                ('CMAQ_ST_DESCRICAO', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição da máquina')),
                ('MAQ_ST_NOME', models.CharField(blank=True, max_length=60, null=True, verbose_name='Centro de Trabalho')),
            ],
            options={
                'db_table': 'Apt_ProMaquinaConfig',
            },
        ),
        migrations.CreateModel(
            name='Apt_ProTipoOrdens',
            fields=[
                ('TPO_ST_ID', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='TPO_ID')),
                ('TPO_ST_CODIGO_TIPO', models.CharField(blank=True, max_length=5, null=True, verbose_name='TIPO DE ORDEM')),
                ('TPO_ST_UNIDADE', models.CharField(blank=True, max_length=8, null=True, verbose_name='UNIDADE CONVERSOR')),
                ('TPO_ST_SELCONVERSOR', models.BooleanField(blank=True, default=True, null=True, verbose_name='SELECIONAR CONVERSOR')),
                ('TPO_ST_OPERACAO', models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='CONFIGURAR OPERACAO')),
                ('TPO_ST_NOME', models.CharField(blank=True, max_length=50, null=True, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'db_table': 'Apt_ProTipoOrdens',
            },
        ),
        migrations.CreateModel(
            name='Car_AtributosReferencia',
            fields=[
                ('CAR_ST_ID', models.CharField(max_length=26, primary_key=True, serialize=False, verbose_name='CAR_ID')),
                ('RAT_ST_ID', models.CharField(blank=True, max_length=13, null=True, verbose_name='id_atributo')),
                ('RFC_ST_ID', models.CharField(blank=True, max_length=13, null=True, verbose_name='id_referência')),
                ('PAI_RAT_IN_CODIGO', models.IntegerField(verbose_name='Atributo Pai')),
                ('RAT_IN_CODIGO', models.IntegerField(verbose_name='Atributo')),
                ('RAT_ST_DESCRICAO', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descrição')),
                ('RAT_VALUE', models.CharField(blank=True, max_length=100, null=True, verbose_name='valores')),
                ('RAT_CH_TIPO', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo')),
                ('CAR_IN_PRIORIDADE', models.IntegerField(blank=True, null=True, verbose_name='prioridade')),
                ('RFC_IN_CODIGO', models.IntegerField(verbose_name='Referência')),
                ('RAT_BO_GRUPO', models.CharField(blank=True, max_length=1, null=True, verbose_name='Grupo')),
                ('CAR_BO_OBRIGATORIO', models.CharField(blank=True, default='S', max_length=1, null=True, verbose_name='Obrigatorio')),
                ('PAI_ST_DESCRICAO', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome_Pai')),
            ],
            options={
                'db_table': 'Car_AtributosReferencia',
            },
        ),
        migrations.AddField(
            model_name='apt_itens_ordens',
            name='PRO_ST_CONVERSOR',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apt_pro_ordens',
            name='TPO_ST_ID',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ID_TPO'),
        ),
    ]
