# Generated by Django 3.2.11 on 2024-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20231030_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='PRO_ST_FORNECEDOR',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
