# Generated by Django 3.2.11 on 2024-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_apt_apontaordem_pro_st_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_apontaordem',
            name='PRO_ST_FORNECEDOR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
