# Generated by Django 6.0.3 on 2026-10-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_apt_apontaordem_pro_st_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_apontaordem',
            name='APT_ST_OBSERV',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='observacoes'),
        ),
        migrations.AddField(
            model_name='apt_apontaordem',
            name='FMT_ST_CODIGO',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='conversor'),
        ),
        migrations.AddField(
            model_name='apt_apontaordem',
            name='MOV_IN_SEQUENCIA',
            field=models.IntegerField(blank=True, null=True, verbose_name='seq_demanda'),
        ),
    ]
