# Generated by Django 3.2.11 on 2022-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apt_Controle',
            fields=[
                ('CTL_IN_CODIGO', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTL_ST_USUARIO', models.CharField(max_length=20)),
                ('ORD_ST_CODIGO', models.CharField(max_length=20)),
                ('CTL_DT_LOGIN', models.DateField()),                
                ('CTL_ST_IPADDRESS', models.CharField(max_length=20)),
                ('CTL_DT_LOGOUT', models.DateField(blank=True, null=True)),
                ('ORD_ST_EXTENSO', models.CharField(blank=True, max_length=20, null=True)),    
            ],
            options={
                'db_table': 'Apt_Controle',
            },
        ),
        migrations.CreateModel(
            name='Apt_Equipamentos',
            fields=[
                ('EQP_IN_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('EQP_ST_NAME', models.CharField(max_length=100)),
                ('EQP_ST_IPADDRESS', models.CharField(max_length=20)),
                ('EQP_IN_FILIAL', models.IntegerField(blank=True, null=True)),
                ('MAQ_IN_CODIGO', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Apt_Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Apt_Pro_CadOperador',
            fields=[
                ('OPD_IN_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('OPD_ST_CRACHA', models.CharField(max_length=20)),
                ('OPD_ST_NOME', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Apt_Pro_CadOperador',
            },
        ),
        migrations.CreateModel(
            name='Apt_Reg_Medidores',
            fields=[
                ('CTL_IN_SEQUENCIA', models.AutoField(primary_key=True, serialize=False)),
                ('CTL_ST_USUARIO', models.CharField(blank=True, max_length=20, null=True)),
                ('ORD_IN_CODIGO', models.IntegerField(blank=True, null=True)),
                ('FIL_IN_CODIGO', models.IntegerField(blank=True, null=True)),
                ('CTL_DT_REGISTRO', models.DateField()),
                ('CTL_ST_IPADDRESS', models.CharField(max_length=20)),
                ('CTL_IN_CONSENERGIA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CTL_IN_PRODUTIVIDADE', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Apt_Reg_Medidores',
            },
        ),
    ]
