# Generated by Django 3.2.11 on 2022-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_controle',
            name='APT_IN_SEQUENCIA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='CTL_ST_STATUS',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        
    ]
