# Generated by Django 3.2.11 on 2022-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0002_auto_20220412_1704'),
    ]

    operations = [        
        migrations.AddField(
            model_name='apt_controle',
            name='APT_DT_ULTAPT',
            field=models.DateField(blank=True, null=True),
        ),            
    ]
