# Generated by Django 3.2.11 on 2022-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0003_auto_20220412_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apt_controle',
            name='ORD_ST_CODIGO',
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='ORD_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_IN_CODIGO',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
