# Generated by Django 3.2.11 on 2022-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0004_auto_20220412_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_controle',
            name='APT_DT_ULTAPT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_DT_LOGIN',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_DT_LOGOUT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
