# Generated by Django 3.2.11 on 2022-04-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0005_auto_20220412_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_IN_CODIGO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
