# Generated by Django 3.2.11 on 2022-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0006_alter_apt_controle_ctl_in_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_controle',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
