# Generated by Django 3.2.11 on 2022-07-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0007_apt_controle_fil_in_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_pro_cadoperador',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='filial'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='APT_IN_SEQUENCIA',
            field=models.IntegerField(blank=True, null=True, verbose_name='apontamento'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_DT_LOGIN',
            field=models.DateTimeField(verbose_name='data acesso'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_DT_LOGOUT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data encerramento'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_IN_CODIGO',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_ST_STATUS',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='CTL_ST_USUARIO',
            field=models.CharField(max_length=20, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='FIL_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='filial'),
        ),
        migrations.AlterField(
            model_name='apt_controle',
            name='ORD_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='apt_equipamentos',
            name='EQP_IN_CODIGO',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='apt_equipamentos',
            name='EQP_IN_FILIAL',
            field=models.IntegerField(blank=True, null=True, verbose_name='filial'),
        ),
        migrations.AlterField(
            model_name='apt_equipamentos',
            name='EQP_ST_IPADDRESS',
            field=models.CharField(max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='apt_equipamentos',
            name='EQP_ST_NAME',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='apt_equipamentos',
            name='MAQ_IN_CODIGO',
            field=models.IntegerField(blank=True, null=True, verbose_name='maquina'),
        ),
        migrations.AlterField(
            model_name='apt_pro_cadoperador',
            name='OPD_IN_CODIGO',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='apt_pro_cadoperador',
            name='OPD_ST_CRACHA',
            field=models.CharField(max_length=20, verbose_name='crachá'),
        ),
        migrations.AlterField(
            model_name='apt_pro_cadoperador',
            name='OPD_ST_NOME',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
