# Generated by Django 3.2.11 on 2022-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0008_auto_20220725_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_equipamentos',
            name='PRINTER_ST_IP',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='impressora'),
        ),
    ]
