# Generated by Django 3.2.11 on 2022-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0009_apt_equipamentos_printer_st_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt_Pro_CadMaquinas',
            fields=[
                ('MAQ_IN_SEQUENCIA', models.AutoField(primary_key=True, serialize=False)),
                ('CTR_ST_ID', models.CharField(max_length=20)),
                ('CMAQ_ST_ID', models.CharField(max_length=20)),
                ('CTR_ST_NOME', models.CharField(max_length=50)),
                ('CMAQ_ST_NOME', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Apt_Pro_CadMaquinas',
            },
        ),
    ]
