# Generated by Django 3.2.11 on 2022-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0010_apt_pro_cadmaquinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_pro_cadmaquinas',
            name='CMAQ_ST_ID',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='apt_pro_cadmaquinas',
            name='CMAQ_ST_NOME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apt_pro_cadmaquinas',
            name='CTR_ST_ID',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='apt_pro_cadmaquinas',
            name='CTR_ST_NOME',
            field=models.CharField(max_length=60),
        ),
    ]
