# Generated by Django 3.2.11 on 2022-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0011_auto_20220923_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_pro_cadmaquinas',
            name='CMAQ_ST_CODIGO',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
