# Generated by Django 3.2.11 on 2022-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0012_apt_pro_cadmaquinas_cmaq_st_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_pro_cadmaquinas',
            name='MAQ_CH_APONTAMNTO',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apt_pro_cadmaquinas',
            name='MAQ_CH_DEMANDA',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
