# Generated by Django 3.2.11 on 2022-09-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0013_auto_20220927_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apt_pro_cadmaquinas',
            old_name='MAQ_CH_APONTAMNTO',
            new_name='MAQ_CH_APONTAMENTO',
        ),
    ]
