# Generated by Django 3.2.11 on 2022-10-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0014_rename_maq_ch_apontamnto_apt_pro_cadmaquinas_maq_ch_apontamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_controle',
            name='CMAQ_ST_ID',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='id_maquina'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='ORD_ST_ID',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='id_ordem'),
        ),
    ]
