# Generated by Django 3.2.11 on 2023-12-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0015_auto_20221011_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_controle',
            name='PRINTER_ST_IP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
