# Generated by Django 6.0.3 on 2026-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamento', '0016_apt_controle_printer_st_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_controle',
            name='CTL_RE_TOTAL_PROD',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='total produzido'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_DT_APONTAMENTO',
            field=models.DateField(blank=True, null=True, verbose_name='data fechamento'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_DT_INCLUSAO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data inclusão'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_HR_FIM',
            field=models.TimeField(blank=True, null=True, verbose_name='hora fim'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_HR_INICIO',
            field=models.TimeField(blank=True, null=True, verbose_name='hora inicio'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_IN_DESC_ALMOCO',
            field=models.IntegerField(blank=True, null=True, verbose_name='desconto almoco (min)'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_IN_DESC_CAFE',
            field=models.IntegerField(blank=True, null=True, verbose_name='desconto cafe (min)'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_IN_TEMPO_LIQUIDO',
            field=models.IntegerField(blank=True, null=True, verbose_name='tempo liquido (min)'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_IN_TEMPO_TOTAL',
            field=models.IntegerField(blank=True, null=True, verbose_name='tempo total (min)'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_RE_QTD_DEMANDAS',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='qtd demandas'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_RE_QTD_PRODUZIDA',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='qtd produzida'),
        ),
        migrations.AddField(
            model_name='apt_controle',
            name='FEC_USU_INCLUSAO',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='usuario inclusão'),
        ),
    ]
