# coding: utf-8
from django.urls import path,re_path
from .views import *

helper_patterns = [
    path('portfolios/', PortfolioListView.as_view(), name='portfolios'),
    re_path(r'^get_portfolio/(?P<pk>[0-9]+)/$', PortfolioView.as_view(), name='get_portfolio'),
    path('get_login/', LoginList.as_view(), name='get_login'),
    path('get_demandas/', Listardemandas.as_view(), name='get_demandas'),
    path('empenhodemandas/', Demandasempenho.as_view(), name='empenhodemandas'),    
    path('oper_ordem/', Operordem.as_view(), name='oper_ordem'),
    path('listarocorrencias/', Listarocorrencias.as_view(), name='listarocorrencias'),
    path('listarproducao/', Listarproducao.as_view(), name='listarproducao'),
    path('listaatributos/', Listaratributos.as_view(), name='listaatributos'),
    path('listareferencias/', Listarreferencias.as_view(), name='listareferencias'),
    path('itensordem/', Itensordem.as_view(), name='itensordem'),    
    path('GetManProOrdens/', GetManProOrdens.as_view(), name='GetManProOrdens'),
    path('GetOrdensPendentes/', GetOrdensPendentes.as_view(), name='GetOrdensPendentes'),
    path('get_demandaordens/', GetDemandaOrdens.as_view(), name='get_demandaordens'),
    path('post_demanda/', IntegrarDemandas.as_view(), name='post_demanda'),
    path('post_producao/', IntegrarApontamento.as_view(), name='post_producao'),
    path('GetCentroCustos/', GetCentroCustos.as_view(), name='GetCentroCustos'),
    path('GetCadastroItens/', GetCadastroItens.as_view(), name='GetCadastroItens'),
    path('geraBaixas/', IntegrarRequisicao.as_view(), name='geraBaixas'),
    path('consultasaldo/', BuscaSaldo.as_view(), name='consultasaldo'),
    path('geraInventario/', IntegrarInventario.as_view(), name='geraInventario'),
    path('GetCadMaquinas/', DadosMaquina.as_view(), name='GetCadMaquinas'),
    path('GetItenslocalizacao/', GetItenslocalizacao.as_view(), name='GetItenslocalizacao'),
    path('GetItensConversor/', GetItensConversor.as_view(), name='GetItensConversor'),
    path('post_integra/', PostAponta.as_view(), name='post_integra'),
    path('post_demandas/', PostDemanda.as_view(), name='post_demandas'),
    path('get_tipoordens/', GetTipoOrdens.as_view(), name='get_tipoordens'),
    path('get_configaponta/', GetConfigAponta.as_view(), name='get_configaponta'),
    path('get_proconversor/', GetProConversor.as_view(), name='get_proconversor'),
    path('get_referencia/', GetProReferencia.as_view(), name='get_referencia'),
    path('avisorecebimento/', GetProRecebimento.as_view(), name='avisorecebimento'),
    path('lotesreceb/', GetLotesReceb.as_view(), name='lotesreceb'),
    path('lotesinvent/', GetLotesInventario.as_view(), name='lotesinvent'),
    #path('PutItenslocalizacao/', PutItenslocalizacao.as_view(), name='PutItenslocalizacao'),
]
urlpatterns = helper_patterns
